{
  "post_stream": {
    "posts": [
      {
        "id": 6964,
        "name": "",
        "username": "tuk",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png",
        "created_at": "2020-05-11T16:09:39.460Z",
        "cooked": "<p>I am running foundation 6.1.12 on Ubuntu 16.04.6 in one of my single node test setup.</p>\n<p>After shutting down the node (with foundationdb running) and starting it I am observing that database is not available. Can someone let me know what could be happening here?<br>\nBelow is the output of <code>status details</code></p>\n<pre><code class=\"lang-auto\">fdb&gt; status details\n\nUsing cluster file `/etc/foundationdb/fdb.cluster'.\n\nLocking coordination state. Verify that a majority of coordination server\nprocesses are active.\n\n  127.0.0.1:4500  (reachable)\n\nUnable to locate the data distributor worker.\n\nUnable to locate the ratekeeper worker.\n</code></pre>\n<p>The output of status json is below</p>\n<pre><code class=\"lang-auto\">{\n    \"client\" : {\n        \"cluster_file\" : {\n            \"path\" : \"/etc/foundationdb/fdb.cluster\",\n            \"up_to_date\" : true\n        },\n        \"coordinators\" : {\n            \"coordinators\" : [\n                {\n                    \"address\" : \"127.0.0.1:4500\",\n                    \"reachable\" : true\n                }\n            ],\n            \"quorum_reachable\" : true\n        },\n        \"database_status\" : {\n            \"available\" : false,\n            \"healthy\" : false\n        },\n        \"messages\" : [\n        ],\n        \"timestamp\" : 1589212043\n    },\n    \"cluster\" : {\n        \"clients\" : {\n            \"count\" : 7,\n            \"supported_versions\" : [\n                {\n                    \"client_version\" : \"6.1.12\",\n                    \"connected_clients\" : [\n                        {\n                            \"address\" : \"127.0.0.1:55764\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        },\n                        {\n                            \"address\" : \"127.0.0.1:55900\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        },\n                        {\n                            \"address\" : \"127.0.0.1:55914\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        },\n                        {\n                            \"address\" : \"127.0.0.1:56078\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        },\n                        {\n                            \"address\" : \"127.0.0.1:56148\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        },\n                        {\n                            \"address\" : \"127.0.0.1:56314\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        },\n                        {\n                            \"address\" : \"127.0.0.1:56450\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        }\n                    ],\n                    \"count\" : 7,\n                    \"protocol_version\" : \"fdb00b061060001\",\n                    \"source_version\" : \"90ba203c166c62ae9173b2523081a0c6afaa1604\"\n                }\n            ]\n        },\n        \"cluster_controller_timestamp\" : 1589212048,\n        \"connection_string\" : \"IqgQyLoo:XrIlR1QY@127.0.0.1:4500\",\n        \"datacenter_version_difference\" : 0,\n        \"degraded_processes\" : 0,\n        \"incompatible_connections\" : [\n        ],\n        \"layers\" : {\n            \"_error\" : \"configurationMissing\",\n            \"_valid\" : false\n        },\n        \"machines\" : {\n            \"3b2ef843117d3dbdfe93ffc023fbf374\" : {\n                \"address\" : \"127.0.0.1\",\n                \"contributing_workers\" : 2,\n                \"cpu\" : {\n                    \"logical_core_utilization\" : 0.0027520600000000002\n                },\n                \"excluded\" : false,\n                \"locality\" : {\n                    \"machineid\" : \"3b2ef843117d3dbdfe93ffc023fbf374\",\n                    \"processid\" : \"4e9fa38cd41ba4893090e422144b30b6\",\n                    \"zoneid\" : \"3b2ef843117d3dbdfe93ffc023fbf374\"\n                },\n                \"machine_id\" : \"3b2ef843117d3dbdfe93ffc023fbf374\",\n                \"memory\" : {\n                    \"committed_bytes\" : 1567232000,\n                    \"free_bytes\" : 15258861568,\n                    \"total_bytes\" : 16826093568\n                },\n                \"network\" : {\n                    \"megabits_received\" : {\n                        \"hz\" : 0.25043499999999996\n                    },\n                    \"megabits_sent\" : {\n                        \"hz\" : 0.25043499999999996\n                    },\n                    \"tcp_segments_retransmitted\" : {\n                        \"hz\" : 0\n                    }\n                }\n            }\n        },\n        \"messages\" : [\n            {\n                \"description\" : \"Unable to locate the data distributor worker.\",\n                \"name\" : \"unreachable_dataDistributor_worker\"\n            },\n            {\n                \"description\" : \"Unable to locate the ratekeeper worker.\",\n                \"name\" : \"unreachable_ratekeeper_worker\"\n            },\n            {\n                \"description\" : \"Unable to read database configuration.\",\n                \"name\" : \"unreadable_configuration\"\n            }\n        ],\n        \"processes\" : {\n            \"4e9fa38cd41ba4893090e422144b30b6\" : {\n                \"address\" : \"127.0.0.1:4500\",\n                \"class_source\" : \"command_line\",\n                \"class_type\" : \"unset\",\n                \"command_line\" : \"/usr/bin/fdbserver --cluster_file=/etc/foundationdb/fdb.cluster --datadir=/var/lib/foundationdb/data/4500 --listen_address=public --logdir=/var/log/foundationdb --public_address=auto:4500\",\n                \"cpu\" : {\n                    \"usage_cores\" : 0.0031999800000000003\n                },\n                \"disk\" : {\n                    \"busy\" : 0,\n                    \"free_bytes\" : 111117496320,\n                    \"reads\" : {\n                        \"counter\" : 52138,\n                        \"hz\" : 0,\n                        \"sectors\" : 0\n                    },\n                    \"total_bytes\" : 117510316032,\n                    \"writes\" : {\n                        \"counter\" : 208806,\n                        \"hz\" : 4.3999699999999997,\n                        \"sectors\" : 176\n                    }\n                },\n                \"fault_domain\" : \"3b2ef843117d3dbdfe93ffc023fbf374\",\n                \"locality\" : {\n                    \"machineid\" : \"3b2ef843117d3dbdfe93ffc023fbf374\",\n                    \"processid\" : \"4e9fa38cd41ba4893090e422144b30b6\",\n                    \"zoneid\" : \"3b2ef843117d3dbdfe93ffc023fbf374\"\n                },\n                \"machine_id\" : \"3b2ef843117d3dbdfe93ffc023fbf374\",\n                \"memory\" : {\n                    \"available_bytes\" : 7881066496,\n                    \"limit_bytes\" : 8589934592,\n                    \"unused_allocated_memory\" : 0,\n                    \"used_bytes\" : 361541632\n                },\n                \"messages\" : [\n                ],\n                \"network\" : {\n                    \"connection_errors\" : {\n                        \"hz\" : 0\n                    },\n                    \"connections_closed\" : {\n                        \"hz\" : 0.19999899999999998\n                    },\n                    \"connections_established\" : {\n                        \"hz\" : 0\n                    },\n                    \"current_connections\" : 5,\n                    \"megabits_received\" : {\n                        \"hz\" : 0.0218783\n                    },\n                    \"megabits_sent\" : {\n                        \"hz\" : 0.011631899999999999\n                    }\n                },\n                \"roles\" : [\n                ],\n                \"uptime_seconds\" : 90985.699999999997,\n                \"version\" : \"6.1.12\"\n            },\n            \"c9c79c494b819706b0eadafdbc15dfd0\" : {\n                \"address\" : \"127.0.0.1:4501\",\n                \"class_source\" : \"command_line\",\n                \"class_type\" : \"stateless\",\n                \"command_line\" : \"/usr/bin/fdbserver --class=stateless --cluster_file=/etc/foundationdb/fdb.cluster --datadir=/var/lib/foundationdb/data/4501 --listen_address=public --logdir=/var/log/foundationdb --public_address=auto:4501\",\n                \"cpu\" : {\n                    \"usage_cores\" : 0.0047999799999999997\n                },\n                \"disk\" : {\n                    \"busy\" : 0,\n                    \"free_bytes\" : 111117496320,\n                    \"reads\" : {\n                        \"counter\" : 52138,\n                        \"hz\" : 0,\n                        \"sectors\" : 0\n                    },\n                    \"total_bytes\" : 117510316032,\n                    \"writes\" : {\n                        \"counter\" : 208806,\n                        \"hz\" : 4.3999800000000002,\n                        \"sectors\" : 176\n                    }\n                },\n                \"fault_domain\" : \"3b2ef843117d3dbdfe93ffc023fbf374\",\n                \"locality\" : {\n                    \"machineid\" : \"3b2ef843117d3dbdfe93ffc023fbf374\",\n                    \"processid\" : \"c9c79c494b819706b0eadafdbc15dfd0\",\n                    \"zoneid\" : \"3b2ef843117d3dbdfe93ffc023fbf374\"\n                },\n                \"machine_id\" : \"3b2ef843117d3dbdfe93ffc023fbf374\",\n                \"memory\" : {\n                    \"available_bytes\" : 7881066496,\n                    \"limit_bytes\" : 8589934592,\n                    \"unused_allocated_memory\" : 0,\n                    \"used_bytes\" : 141729792\n                },\n                \"messages\" : [\n                ],\n                \"network\" : {\n                    \"connection_errors\" : {\n                        \"hz\" : 0\n                    },\n                    \"connections_closed\" : {\n                        \"hz\" : 0.19999899999999998\n                    },\n                    \"connections_established\" : {\n                        \"hz\" : 0\n                    },\n                    \"current_connections\" : 5,\n                    \"megabits_received\" : {\n                        \"hz\" : 0.034758199999999996\n                    },\n                    \"megabits_sent\" : {\n                        \"hz\" : 0.047089399999999997\n                    }\n                },\n                \"roles\" : [\n                    {\n                        \"id\" : \"c7a0a4b137cf2015\",\n                        \"role\" : \"master\"\n                    },\n                    {\n                        \"id\" : \"956b61b1e846510d\",\n                        \"role\" : \"cluster_controller\"\n                    }\n                ],\n                \"uptime_seconds\" : 90985.699999999997,\n                \"version\" : \"6.1.12\"\n            }\n        },\n        \"protocol_version\" : \"fdb00b061060001\",\n        \"recovery_state\" : {\n            \"description\" : \"Locking coordination state. Verify that a majority of coordination server processes are active.\",\n            \"name\" : \"locking_coordinated_state\"\n        }\n    }\n}\n</code></pre>\n<p>I am not seeing any trace with Severity 30 and Severity 40 in the fdb traces log. I have placed the logs <a href=\"https://drive.google.com/uc?id=1tT0GcnO9J-632rsqNb3I4odAyXeBW1cF&amp;export=download\" rel=\"nofollow noopener\">here</a></p>\n<p>My foundationdb.conf looks like below</p>\n<pre><code class=\"lang-auto\">[fdbmonitor]\nuser = ubuntu\ngroup = ubuntu\n\n\n[general]\nrestart_delay = 60\ncluster_file = /etc/foundationdb/fdb.cluster\n\n\n[fdbserver]\ncommand = /usr/bin/fdbserver\npublic_address = auto:$ID\nlisten_address = public\ndatadir = /var/lib/foundationdb/data/$ID\nlogdir = /var/log/foundationdb\n\n\n[fdbserver.4500]\n\n\n[fdbserver.4501]\nclass = stateless\n\n\n[backup_agent]\ncommand = /usr/lib/foundationdb/backup_agent/backup_agent\nlogdir = /var/log/foundationdb\n\n[backup_agent.1]\n</code></pre>",
        "post_number": 1,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-05-12T05:24:52.187Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 841,
        "reads": 94,
        "readers_count": 93,
        "score": 4223.8,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 2,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://drive.google.com/uc?id=1tT0GcnO9J-632rsqNb3I4odAyXeBW1cF&export=download",
            "internal": false,
            "reflection": false,
            "clicks": 5
          }
        ],
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 714,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/1",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null,
        "can_vote": false
      },
      {
        "id": 6977,
        "name": "",
        "username": "tuk",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png",
        "created_at": "2020-05-12T05:29:24.992Z",
        "cooked": "<p><a class=\"mention\" href=\"/u/ajbeamon\">@ajbeamon</a> <a class=\"mention\" href=\"/u/alexmiller\">@alexmiller</a> - I see someone reported something similar in <a href=\"https://forums.foundationdb.org/t/can-i-remove-a-process/1428/7\" class=\"inline-onebox\">Can I remove a process?</a> . But then no conclusion has been reached there. Any suggestion what may have gone wrong here?</p>",
        "post_number": 2,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-05-12T05:29:24.992Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 80,
        "readers_count": 79,
        "score": 21.0,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://forums.foundationdb.org/t/can-i-remove-a-process/1428/7",
            "internal": true,
            "reflection": false,
            "title": "Can I remove a process?",
            "clicks": 13
          }
        ],
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 714,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/2",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6981,
        "name": "A.J. Beamon",
        "username": "ajbeamon",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
        "created_at": "2020-05-12T16:42:39.067Z",
        "cooked": "<p>The logs here are a bit incomplete (they don\u2019t contain the events at the beginning of the recovery), but I do see a lot of messages about connections failing. If your processes can\u2019t talk to each other, then that could prevent the cluster from recovering.</p>",
        "post_number": 3,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-05-12T16:42:39.067Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 78,
        "readers_count": 77,
        "score": 20.6,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "A.J. Beamon",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": true,
        "staff": true,
        "user_id": 12,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/3",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6982,
        "name": "",
        "username": "tuk",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png",
        "created_at": "2020-05-12T17:14:19.031Z",
        "cooked": "<p>Thanks <a class=\"mention\" href=\"/u/ajbeamon\">@ajbeamon</a> for replying.</p>\n<p>This is a single node setup.</p>\n<p>Any suggestion how can I recover the database?</p>\n<p>I tried stopping and starting fdbmonitor multiple times but still same issue.</p>",
        "post_number": 4,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-05-12T17:15:08.251Z",
        "reply_count": 0,
        "reply_to_post_number": 3,
        "quote_count": 0,
        "incoming_link_count": 2,
        "reads": 79,
        "readers_count": 78,
        "score": 25.8,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 12,
          "username": "ajbeamon",
          "name": "A.J. Beamon",
          "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 714,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/4",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 6983,
        "name": "A.J. Beamon",
        "username": "ajbeamon",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
        "created_at": "2020-05-12T17:17:31.142Z",
        "cooked": "<p>You do have multiple processes running, and they are reporting connection failures, possibly with talking to each other. It\u2019s hard for me to say why that is happening, but it could be relevant.</p>",
        "post_number": 5,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-05-12T17:17:31.142Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 80,
        "readers_count": 79,
        "score": 21.0,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "A.J. Beamon",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": true,
        "staff": true,
        "user_id": 12,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/5",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 7284,
        "name": "",
        "username": "tuk",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png",
        "created_at": "2020-06-09T19:17:49.506Z",
        "cooked": "<p><a class=\"mention\" href=\"/u/ajbeamon\">@ajbeamon</a> I got this issue again. Shutting down a VM running foundationdb and then starting it, making the database unavailable.</p>\n<pre><code class=\"lang-auto\">ubuntu@vrni-proxy-release:~$ fdbcli\nUsing cluster file `fdb.cluster'.\n\nThe database is unavailable; type `status' for more information.\n\nWelcome to the fdbcli. For help, type `help'.\nfdb&gt; status details\n\nUsing cluster file `fdb.cluster'.\n\nLocking coordination state. Verify that a majority of coordination server\nprocesses are active.\n\n  127.0.0.1:4500  (reachable)\n\nUnable to locate the data distributor worker.\n\nUnable to locate the ratekeeper worker.\n\nfdb&gt;\n</code></pre>\n<p><code>foundationdb.conf</code> same as in posted above.</p>\n<pre><code class=\"lang-auto\">ubuntu@vrni-proxy-release:~$ who -b\n         system boot  2020-06-09 18:40\nubuntu@vrni-proxy-release:~$ lsb_release -a\nNo LSB modules are available.\nDistributor ID:\tUbuntu\nDescription:\tUbuntu 16.04.6 LTS\nRelease:\t16.04\nCodename:\txenial\n</code></pre>\n<p>FoundationDB Version - 6.1.12</p>\n<p>Once I hit this issue . Then I could not find anyway to recover the database.</p>\n<p>I have to stop the foundationdb , delete the entire data directory of foundationdb. Create a new <code>/etc/foundationdb/fdb.cluster</code> with content like below and start the foundationdb again.</p>\n<pre><code class=\"lang-auto\">IqgQyLoo:XrIlR1QY@127.0.0.1:4500\n</code></pre>\n<p>Once I perform the above steps then foundationdb again becomes operational. So I think when I am shutting down the VM some data may be getting corrupted in foundationdb which is making the database completely unusable. The fdb logs are also not helping me much.</p>\n<p>I have placed the content of the fdb data directory, logs and fdb.cluster file <a href=\"https://drive.google.com/drive/folders/1bqElC70rm3Fxuihoou37ULJUZIdz62Fy?usp=sharing\" rel=\"nofollow noopener\">here</a>.</p>\n<p>Output of <code>status json</code></p>\n<pre><code class=\"lang-auto\">{\n    \"client\" : {\n        \"cluster_file\" : {\n            \"path\" : \"fdb.cluster\",\n            \"up_to_date\" : true\n        },\n        \"coordinators\" : {\n            \"coordinators\" : [\n                {\n                    \"address\" : \"127.0.0.1:4500\",\n                    \"reachable\" : true\n                }\n            ],\n            \"quorum_reachable\" : true\n        },\n        \"database_status\" : {\n            \"available\" : false,\n            \"healthy\" : false\n        },\n        \"messages\" : [\n        ],\n        \"timestamp\" : 1591729978\n    },\n    \"cluster\" : {\n        \"clients\" : {\n            \"count\" : 8,\n            \"supported_versions\" : [\n                {\n                    \"client_version\" : \"6.1.12\",\n                    \"connected_clients\" : [\n                        {\n                            \"address\" : \"127.0.0.1:53980\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        },\n                        {\n                            \"address\" : \"127.0.0.1:54076\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        },\n                        {\n                            \"address\" : \"127.0.0.1:54086\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        },\n                        {\n                            \"address\" : \"127.0.0.1:54266\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        },\n                        {\n                            \"address\" : \"127.0.0.1:54364\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        },\n                        {\n                            \"address\" : \"127.0.0.1:54504\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        },\n                        {\n                            \"address\" : \"127.0.0.1:54656\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        },\n                        {\n                            \"address\" : \"127.0.0.1:54756\",\n                            \"connected_coordinators\" : 1,\n                            \"log_group\" : \"default\"\n                        }\n                    ],\n                    \"count\" : 8,\n                    \"protocol_version\" : \"fdb00b061060001\",\n                    \"source_version\" : \"90ba203c166c62ae9173b2523081a0c6afaa1604\"\n                }\n            ]\n        },\n        \"cluster_controller_timestamp\" : 1591729983,\n        \"connection_string\" : \"IqgQyLoo:XrIlR1QY@127.0.0.1:4500\",\n        \"datacenter_version_difference\" : 0,\n        \"degraded_processes\" : 0,\n        \"incompatible_connections\" : [\n        ],\n        \"layers\" : {\n            \"_error\" : \"configurationMissing\",\n            \"_valid\" : false\n        },\n        \"machines\" : {\n            \"b1da0c3824d31c5a3f861b1df636d474\" : {\n                \"address\" : \"127.0.0.1\",\n                \"contributing_workers\" : 2,\n                \"cpu\" : {\n                    \"logical_core_utilization\" : 0.010020000000000001\n                },\n                \"excluded\" : false,\n                \"locality\" : {\n                    \"machineid\" : \"b1da0c3824d31c5a3f861b1df636d474\",\n                    \"processid\" : \"cbffdce3940166e1b61a4b5253a05a49\",\n                    \"zoneid\" : \"b1da0c3824d31c5a3f861b1df636d474\"\n                },\n                \"machine_id\" : \"b1da0c3824d31c5a3f861b1df636d474\",\n                \"memory\" : {\n                    \"committed_bytes\" : 1253486592,\n                    \"free_bytes\" : 11345350656,\n                    \"total_bytes\" : 12598837248\n                },\n                \"network\" : {\n                    \"megabits_received\" : {\n                        \"hz\" : 0.30287799999999998\n                    },\n                    \"megabits_sent\" : {\n                        \"hz\" : 0.30287799999999998\n                    },\n                    \"tcp_segments_retransmitted\" : {\n                        \"hz\" : 0\n                    }\n                }\n            }\n        },\n        \"messages\" : [\n            {\n                \"description\" : \"Unable to locate the data distributor worker.\",\n                \"name\" : \"unreachable_dataDistributor_worker\"\n            },\n            {\n                \"description\" : \"Unable to locate the ratekeeper worker.\",\n                \"name\" : \"unreachable_ratekeeper_worker\"\n            },\n            {\n                \"description\" : \"Unable to read database configuration.\",\n                \"name\" : \"unreadable_configuration\"\n            }\n        ],\n        \"processes\" : {\n            \"1562ed9ef68b4b22c344ad858ed8876a\" : {\n                \"address\" : \"127.0.0.1:4501\",\n                \"class_source\" : \"command_line\",\n                \"class_type\" : \"stateless\",\n                \"command_line\" : \"/usr/bin/fdbserver --class=stateless --cluster_file=/etc/foundationdb/fdb.cluster --datadir=/var/lib/foundationdb/data/4501 --listen_address=public --logdir=/var/log/foundationdb --public_address=auto:4501\",\n                \"cpu\" : {\n                    \"usage_cores\" : 0.0055999800000000001\n                },\n                \"disk\" : {\n                    \"busy\" : 0,\n                    \"free_bytes\" : 111130923008,\n                    \"reads\" : {\n                        \"counter\" : 802,\n                        \"hz\" : 0,\n                        \"sectors\" : 0\n                    },\n                    \"total_bytes\" : 117510316032,\n                    \"writes\" : {\n                        \"counter\" : 1461,\n                        \"hz\" : 2.3999899999999998,\n                        \"sectors\" : 96\n                    }\n                },\n                \"fault_domain\" : \"b1da0c3824d31c5a3f861b1df636d474\",\n                \"locality\" : {\n                    \"machineid\" : \"b1da0c3824d31c5a3f861b1df636d474\",\n                    \"processid\" : \"1562ed9ef68b4b22c344ad858ed8876a\",\n                    \"zoneid\" : \"b1da0c3824d31c5a3f861b1df636d474\"\n                },\n                \"machine_id\" : \"b1da0c3824d31c5a3f861b1df636d474\",\n                \"memory\" : {\n                    \"available_bytes\" : 5919866880,\n                    \"limit_bytes\" : 8589934592,\n                    \"unused_allocated_memory\" : 0,\n                    \"used_bytes\" : 133255168\n                },\n                \"messages\" : [\n                ],\n                \"network\" : {\n                    \"connection_errors\" : {\n                        \"hz\" : 0\n                    },\n                    \"connections_closed\" : {\n                        \"hz\" : 0.19999899999999998\n                    },\n                    \"connections_established\" : {\n                        \"hz\" : 0\n                    },\n                    \"current_connections\" : 5,\n                    \"megabits_received\" : {\n                        \"hz\" : 0.0335535\n                    },\n                    \"megabits_sent\" : {\n                        \"hz\" : 0.046278199999999999\n                    }\n                },\n                \"roles\" : [\n                    {\n                        \"id\" : \"d8b1d66f1128667d\",\n                        \"role\" : \"master\"\n                    },\n                    {\n                        \"id\" : \"169b474905a518f7\",\n                        \"role\" : \"cluster_controller\"\n                    }\n                ],\n                \"uptime_seconds\" : 1905.01,\n                \"version\" : \"6.1.12\"\n            },\n            \"cbffdce3940166e1b61a4b5253a05a49\" : {\n                \"address\" : \"127.0.0.1:4500\",\n                \"class_source\" : \"command_line\",\n                \"class_type\" : \"unset\",\n                \"command_line\" : \"/usr/bin/fdbserver --cluster_file=/etc/foundationdb/fdb.cluster --datadir=/var/lib/foundationdb/data/4500 --listen_address=public --logdir=/var/log/foundationdb --public_address=auto:4500\",\n                \"cpu\" : {\n                    \"usage_cores\" : 0.0031999900000000002\n                },\n                \"disk\" : {\n                    \"busy\" : 0,\n                    \"free_bytes\" : 111130923008,\n                    \"reads\" : {\n                        \"counter\" : 802,\n                        \"hz\" : 0,\n                        \"sectors\" : 0\n                    },\n                    \"total_bytes\" : 117510316032,\n                    \"writes\" : {\n                        \"counter\" : 1461,\n                        \"hz\" : 2.3999999999999999,\n                        \"sectors\" : 96\n                    }\n                },\n                \"fault_domain\" : \"b1da0c3824d31c5a3f861b1df636d474\",\n                \"locality\" : {\n                    \"machineid\" : \"b1da0c3824d31c5a3f861b1df636d474\",\n                    \"processid\" : \"cbffdce3940166e1b61a4b5253a05a49\",\n                    \"zoneid\" : \"b1da0c3824d31c5a3f861b1df636d474\"\n                },\n                \"machine_id\" : \"b1da0c3824d31c5a3f861b1df636d474\",\n                \"memory\" : {\n                    \"available_bytes\" : 5919866880,\n                    \"limit_bytes\" : 8589934592,\n                    \"unused_allocated_memory\" : 0,\n                    \"used_bytes\" : 361127936\n                },\n                \"messages\" : [\n                ],\n                \"network\" : {\n                    \"connection_errors\" : {\n                        \"hz\" : 0\n                    },\n                    \"connections_closed\" : {\n                        \"hz\" : 0.20000000000000001\n                    },\n                    \"connections_established\" : {\n                        \"hz\" : 0\n                    },\n                    \"current_connections\" : 5,\n                    \"megabits_received\" : {\n                        \"hz\" : 0.021672\n                    },\n                    \"megabits_sent\" : {\n                        \"hz\" : 0.011384\n                    }\n                },\n                \"roles\" : [\n                ],\n                \"uptime_seconds\" : 1905.0699999999999,\n                \"version\" : \"6.1.12\"\n            }\n        },\n        \"protocol_version\" : \"fdb00b061060001\",\n        \"recovery_state\" : {\n            \"description\" : \"Locking coordination state. Verify that a majority of coordination server processes are active.\",\n            \"name\" : \"locking_coordinated_state\"\n        }\n    }\n}\n</code></pre>\n<p>I am maintaining the VM in that state. I can help in performing some tests that may help in debugging this issue.</p>\n<p>Do you think I should file an issue for this?</p>",
        "post_number": 6,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-06-09T19:21:00.757Z",
        "reply_count": 0,
        "reply_to_post_number": 5,
        "quote_count": 0,
        "incoming_link_count": 13,
        "reads": 74,
        "readers_count": 73,
        "score": 94.8,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://drive.google.com/drive/folders/1bqElC70rm3Fxuihoou37ULJUZIdz62Fy?usp=sharing",
            "internal": false,
            "reflection": false,
            "title": "fdb_corrupt - Google Drive",
            "clicks": 4
          }
        ],
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 12,
          "username": "ajbeamon",
          "name": "A.J. Beamon",
          "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png"
        },
        "bookmarked": false,
        "actions_summary": [
          {
            "id": 2,
            "count": 1
          }
        ],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 714,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/6",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 7285,
        "name": "A.J. Beamon",
        "username": "ajbeamon",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
        "created_at": "2020-06-09T20:37:27.996Z",
        "cooked": "<p>Any idea what\u2019s going on with the trace log <code>trace.127.0.0.1.4500.1591509270.KBigDP.1.xml</code>? It just has a bunch of null bytes in it. I\u2019m also wondering whether something weird happened during that incarnation of the process, as things looked ok before it and didn\u2019t work after it.</p>",
        "post_number": 7,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-06-09T20:37:27.996Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 69,
        "readers_count": 68,
        "score": 18.8,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "A.J. Beamon",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": true,
        "staff": true,
        "user_id": 12,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/7",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 7288,
        "name": "",
        "username": "tuk",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png",
        "created_at": "2020-06-10T06:02:41.567Z",
        "cooked": "<p><a class=\"mention\" href=\"/u/ajbeamon\">@ajbeamon</a> - Just to add this just a fdb single node cluster with very less data. Probably this situation can be recreated if someone tries to start a single node fdb cluster using the given Cluster and data files.</p>\n<blockquote>\n<p>Any idea what\u2019s going on with the trace log  <code>trace.127.0.0.1.4500.1591509270.KBigDP.1.xml</code> ?</p>\n</blockquote>\n<p>No. I did not modify anything on the files.  It was like that only.</p>\n<blockquote>\n<p>I\u2019m also wondering whether something weird happened during that incarnation of the process, as things looked ok before it and didn\u2019t work after it.</p>\n</blockquote>\n<p>Yes everything was fine before. Now if I wipe out everything from foundationdb data directory fdb will again start to work properly.</p>",
        "post_number": 8,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-06-10T08:27:39.269Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 2,
        "reads": 69,
        "readers_count": 68,
        "score": 23.8,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 2,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 714,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/8",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 7292,
        "name": "",
        "username": "tuk",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png",
        "created_at": "2020-06-10T12:14:38.358Z",
        "cooked": "<p>I am able to repro the same cluster state in a healthy fdb single node cluster (on ubuntu 16.04.6) by using the data and cluster file which I have shared. Steps followed</p>\n<ol>\n<li>Shutdown foundation db</li>\n<li>Replace <code>/etc/foundationdb/foundationdb.conf</code> with the one posted above.</li>\n<li>Note the permission of all files under <code>/var/lib/foundationdb/data</code>\n</li>\n<li>Replace <code>/var/lib/foundationdb/data</code> with the content of the <code>fdb_data.tar.gz</code> which was shared.</li>\n<li>Make the permission of all files under <code>/var/lib/foundationdb/data</code> same as the permission noted in Step 3.</li>\n<li>Replace <code>/etc/foundationdb/fdb.cluster</code> with the content of the <code>fdb.cluster</code> file I shared.</li>\n<li>Start foundationdb</li>\n</ol>\n<p>Just to rule out that there are no errors in the above steps. I have performed the above steps by using data and cluster file from a healthy single node fdb cluster. Things work fine and this one becomes a copy of the cluster from where data is copied. Only when I use this faulty data and cluster file I see the problem.</p>",
        "post_number": 9,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-06-10T12:23:07.014Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 3,
        "reads": 67,
        "readers_count": 66,
        "score": 33.4,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 2,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 714,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/9",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 7294,
        "name": "A.J. Beamon",
        "username": "ajbeamon",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
        "created_at": "2020-06-10T15:16:12.577Z",
        "cooked": "<p>Yeah, I was able to reproduce the stuck cluster from your data files as well (these were helpful, thank you), from which I can see there is some problem trying to recover from a transaction log. It\u2019s not clear to me yet what exactly has happened though, and I suspect some of the interesting details occurred during the period when the transaction logs are invalid.</p>\n<p>If something weird has happened to the log files, I wonder if something bad has also happened to your data files, and what the nature of that damage might be. It doesn\u2019t seem as if your data files are completely destroyed, though, like the log file is. If you ever get a reproduction where the log files are complete, I\u2019d be very interested to see them.</p>",
        "post_number": 10,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-06-10T15:16:12.577Z",
        "reply_count": 1,
        "reply_to_post_number": 9,
        "quote_count": 0,
        "incoming_link_count": 4,
        "reads": 67,
        "readers_count": 66,
        "score": 38.4,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "A.J. Beamon",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 714,
          "username": "tuk",
          "name": "",
          "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": true,
        "staff": true,
        "user_id": 12,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/10",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 7297,
        "name": "",
        "username": "tuk",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png",
        "created_at": "2020-06-10T16:15:52.608Z",
        "cooked": "<p><a class=\"mention\" href=\"/u/ajbeamon\">@ajbeamon</a> -  Is there a way to remove/reset the tlog files, with an understanding that it will cause data loss for any transaction that is not yet applied on storage servers.?</p>\n<p>Some of our deployments are single node, so if we hit this issue I would like to come out with whatever can be salvaged.</p>",
        "post_number": 11,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-06-10T16:22:59.978Z",
        "reply_count": 0,
        "reply_to_post_number": 10,
        "quote_count": 0,
        "incoming_link_count": 1,
        "reads": 63,
        "readers_count": 62,
        "score": 17.6,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 2,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 12,
          "username": "ajbeamon",
          "name": "A.J. Beamon",
          "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 714,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/11",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 7298,
        "name": "A.J. Beamon",
        "username": "ajbeamon",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
        "created_at": "2020-06-10T16:22:44.492Z",
        "cooked": "<p>At present, no, though there\u2019s a proposed issue for recovering from a partial set of files:</p>\n<aside class=\"onebox githubissue\">\n  <header class=\"source\">\n      <a href=\"https://github.com/apple/foundationdb/issues/2480\" target=\"_blank\">github.com/apple/foundationdb</a>\n  </header>\n  <article class=\"onebox-body\">\n    <div class=\"github-row\">\n  <div class=\"github-icon-container\" title=\"Issue\">\n\t  <svg width=\"60\" height=\"60\" class=\"github-icon\" viewBox=\"0 0 14 16\" aria-hidden=\"true\"><path d=\"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z\"></path></svg>\n  </div>\n\n  <div class=\"github-info-container\">\n    <h4>\n      <a href=\"https://github.com/apple/foundationdb/issues/2480\" target=\"_blank\">Provide tooling to recover from a corrupted (non-recoverable) fdb cluster</a>\n    </h4>\n\n    <div class=\"github-info\">\n      <div class=\"date\">\n        opened <span class=\"discourse-local-date\" data-format=\"ll\" data-date=\"2019-12-18\" data-time=\"17:28:07\" data-timezone=\"UTC\">05:28PM - 18 Dec 19 UTC</span>\n      </div>\n\n\n      <div class=\"user\">\n        <a href=\"https://github.com/mpilman\" target=\"_blank\">\n          <img alt=\"mpilman\" src=\"https://global.discourse-cdn.com/foundationdb/original/1X/f7272c6cb89b34a7cb45e5a0811716c76d52985d.png\" class=\"onebox-avatar-inline\" width=\"20\" height=\"20\">\n          mpilman\n        </a>\n      </div>\n    </div>\n  </div>\n</div>\n\n<div class=\"github-row\">\n  <p class=\"github-content\">There are several ways we can corrupt a cluster without losing a majority of data:\nWe could lose enough tlogs so that...</p>\n</div>\n\n<div class=\"labels\">\n</div>\n\n  </article>\n  <div class=\"onebox-metadata\">\n    \n    \n  </div>\n  <div style=\"clear: both\"></div>\n</aside>\n\n<p>In your case, though, I\u2019d really like to understand what\u2019s happening and resolve the root problem such that you aren\u2019t running into these issues. Is there anything of note you can say about the process that causes this? How easily can you reproduce the behavior starting from a working cluster?</p>",
        "post_number": 12,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-06-10T16:22:44.492Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 2,
        "reads": 62,
        "readers_count": 61,
        "score": 27.4,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "A.J. Beamon",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "link_counts": [
          {
            "url": "https://github.com/apple/foundationdb/issues/2480",
            "internal": false,
            "reflection": false,
            "title": "Provide tooling to recover from a corrupted (non-recoverable) fdb cluster \u00b7 Issue #2480 \u00b7 apple/foundationdb \u00b7 GitHub",
            "clicks": 21
          },
          {
            "url": "https://github.com/mpilman",
            "internal": false,
            "reflection": false,
            "clicks": 0
          }
        ],
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": true,
        "staff": true,
        "user_id": 12,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/12",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 7299,
        "name": "",
        "username": "tuk",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png",
        "created_at": "2020-06-10T17:00:45.079Z",
        "cooked": "<p>It is not very frequent.</p>\n<p>In our environment Fdb runs on a Ubuntu (16.04.6) VM on VMWare ESXi virtualized environment.</p>\n<p>The pattern was same in all the cases. In a single node deployment of foundationdb shut down the VM with foundationdb processes running (using <code>shutdown</code> command). We have not seen this issue in any of our clustered deployment so far.</p>",
        "post_number": 13,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-06-10T17:00:45.079Z",
        "reply_count": 1,
        "reply_to_post_number": 12,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 61,
        "readers_count": 60,
        "score": 17.2,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 12,
          "username": "ajbeamon",
          "name": "A.J. Beamon",
          "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 714,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/13",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 7317,
        "name": "",
        "username": "tuk",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png",
        "created_at": "2020-06-11T12:35:17.530Z",
        "cooked": "<p>I will try to repro the problem and once I am able to do it, I will get back with more logs.</p>",
        "post_number": 14,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-06-11T12:35:17.530Z",
        "reply_count": 0,
        "reply_to_post_number": 13,
        "quote_count": 0,
        "incoming_link_count": 0,
        "reads": 60,
        "readers_count": 59,
        "score": 12.0,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 714,
          "username": "tuk",
          "name": "",
          "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 714,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/14",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 7319,
        "name": "A.J. Beamon",
        "username": "ajbeamon",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
        "created_at": "2020-06-11T21:04:55.952Z",
        "cooked": "<p>Ok, thank you. I\u2019ll take a further look at the results that you provided to see if anything else pops out at me.</p>",
        "post_number": 15,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2020-06-11T21:04:55.952Z",
        "reply_count": 1,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 8,
        "reads": 63,
        "readers_count": 62,
        "score": 57.6,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "A.J. Beamon",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": true,
        "staff": true,
        "user_id": 12,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/15",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 9001,
        "name": "Amanda",
        "username": "amanda",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/a/67e7ee/{size}.png",
        "created_at": "2021-01-28T20:38:28.942Z",
        "cooked": "<p>Hi, I hit this issue on one of my kubernetes FDB clusters. (We\u2019re not using the official fdb operator)</p>\n<p>The TLog error seemed to be because we ran out of memory:</p>\n<pre><code class=\"lang-auto\">&lt;Event Severity=\"30\" Time=\"1611857459.869919\" Type=\"AbsolutePathError\" ID=\"0000000000000000\" Path=\"/storage/var/data/4500/logqueue-V_3_LS_2-82e69f55d06bdc2fdbe35467c6618dda-\" UnixErrorCode=\"c\" UnixError=\"Cannot allocate memory\" Error=\"platform_error\" ErrorDescription=\"Platform error\" ErrorCode=\"1500\" Machine=\"10.0.1.64:4500\" LogGroup=\"default\" Roles=\"MP,RV,SS,TL\" /&gt;\n</code></pre>\n<p>(Something else on the host started eating memory, the memory usage reported by FDB was around 40% of its 8GB max)</p>\n<p>I checked that the log file its trying to access exists and similarly to what was reported here, after restarts and ensuring proper memory resources I wasn\u2019t able to get the DB back.</p>\n<p>No idea if this was a coincidence, doesn\u2019t seem to make much sense to me\u2013but I ran a <code>setclass</code> in fdbcli on another node just to list the processes. It took a super long time but did return properly, and then the cluster immediately became functional after that. Would something about getting the workers force the bad fdbserver to retry the tlog or something like that?</p>",
        "post_number": 16,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2021-01-28T20:38:28.942Z",
        "reply_count": 1,
        "reply_to_post_number": 15,
        "quote_count": 0,
        "incoming_link_count": 4,
        "reads": 59,
        "readers_count": 58,
        "score": 36.8,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "Amanda",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 12,
          "username": "ajbeamon",
          "name": "A.J. Beamon",
          "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png"
        },
        "bookmarked": false,
        "actions_summary": [],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 810,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/16",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 9007,
        "name": "Alex Miller",
        "username": "alexmiller",
        "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
        "created_at": "2021-01-28T22:50:03.323Z",
        "cooked": "<p>That\u2019s an error that calling <code>abspath()</code> returned with an error that it couldn\u2019t allocate the memory required to hold the string for the return value.  That\u2019s an indication that something either in the kubernetes container, or on the host outside of the container, was eating so much memory that malloc() failed.</p>\n<p>Listing processes requires a cluster controller to exist, which also probably means the cluster to be mostly up and available.  I\u2019d be suspicious that a similar thing was happening on other machines, or that your machines were swapping themselves to death and thus exceedingly slow, and that something like that impeded FDB\u2019s ability to recover and get back to being available.</p>",
        "post_number": 17,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2021-01-28T22:50:03.323Z",
        "reply_count": 0,
        "reply_to_post_number": 16,
        "quote_count": 0,
        "incoming_link_count": 8,
        "reads": 57,
        "readers_count": 56,
        "score": 66.4,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "Alex Miller",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 1,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "reply_to_user": {
          "id": 810,
          "username": "amanda",
          "name": "Amanda",
          "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/a/67e7ee/{size}.png"
        },
        "bookmarked": false,
        "actions_summary": [
          {
            "id": 2,
            "count": 1
          }
        ],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 13,
        "hidden": false,
        "trust_level": 4,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/17",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      },
      {
        "id": 9049,
        "name": "Amanda",
        "username": "amanda",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/a/67e7ee/{size}.png",
        "created_at": "2021-02-05T22:16:50.767Z",
        "cooked": "<p>Ah, this happened again and I got to investigate a bit more. Same thing - one fdbserver ran out of memory. I noticed something interesting - When this happens it totally prevents any log/proxy/storage from being recruited. I checked status json while the cluster was in its unavailable state and there were no log/proxy/storage roles in the cluster. Looks like CC (which was not on the fdbserver that went down) was getting RegisterWorkerRequests but not RecruitStorageRequests? I first wondered if CC was in a weird state and stopped retrying so I killed that fdbserver and another one got recruited as CC and had the same issue.</p>\n<p>Also fdbservers were showing <code>SS</code> roles in their logs but not in the <code>status json</code> output.</p>\n<p>It makes sense that a fdbserver running out of memory requires it to be restarted, but I\u2019m surprised it surfaced as a <code>Locking coordination state. Verify that a majority of coordination server processes are active.</code> error when it was not a coordinator (it was DD and ratekeeper)</p>\n<p>Also, I believe fdbserver will bounce itself if it runs out of its configured memory, but it won\u2019t do this if it runs out of available memory (if the full amount of configured memory is not available on the host). It does track the available memory though, I saw it being reported in the log as &lt;1GB when it went down. Has anyone considered also bouncing fdbserver if it runs low on available memory as well?</p>",
        "post_number": 18,
        "post_type": 1,
        "posts_count": 18,
        "updated_at": "2021-02-05T22:18:40.764Z",
        "reply_count": 0,
        "reply_to_post_number": null,
        "quote_count": 0,
        "incoming_link_count": 2,
        "reads": 52,
        "readers_count": 51,
        "score": 35.4,
        "yours": false,
        "topic_id": 2113,
        "topic_slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
        "display_username": "Amanda",
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_bg_color": null,
        "flair_color": null,
        "flair_group_id": null,
        "badges_granted": [],
        "version": 2,
        "can_edit": false,
        "can_delete": false,
        "can_recover": false,
        "can_see_hidden_post": false,
        "can_wiki": false,
        "read": true,
        "user_title": null,
        "bookmarked": false,
        "actions_summary": [
          {
            "id": 2,
            "count": 1
          }
        ],
        "moderator": false,
        "admin": false,
        "staff": false,
        "user_id": 810,
        "hidden": false,
        "trust_level": 2,
        "deleted_at": null,
        "user_deleted": false,
        "edit_reason": null,
        "can_view_edit_history": true,
        "wiki": false,
        "post_url": "/t/database-unavailable-after-shutting-down-a-foundationdb-node/2113/18",
        "can_accept_answer": false,
        "can_unaccept_answer": false,
        "accepted_answer": false,
        "topic_accepted_answer": null
      }
    ],
    "stream": [
      6964,
      6977,
      6981,
      6982,
      6983,
      7284,
      7285,
      7288,
      7292,
      7294,
      7297,
      7298,
      7299,
      7317,
      7319,
      9001,
      9007,
      9049
    ]
  },
  "timeline_lookup": [
    [
      1,
      1989
    ],
    [
      3,
      1988
    ],
    [
      6,
      1960
    ],
    [
      9,
      1959
    ],
    [
      14,
      1958
    ],
    [
      16,
      1727
    ],
    [
      18,
      1719
    ]
  ],
  "suggested_topics": [],
  "tags": [],
  "tags_descriptions": {},
  "fancy_title": "Database unavailable after shutting down a foundationdb node",
  "id": 2113,
  "title": "Database unavailable after shutting down a foundationdb node",
  "posts_count": 18,
  "created_at": "2020-05-11T16:09:39.373Z",
  "views": 8569,
  "reply_count": 8,
  "like_count": 3,
  "last_posted_at": "2021-02-05T22:16:50.767Z",
  "visible": true,
  "closed": false,
  "archived": false,
  "has_summary": false,
  "archetype": "regular",
  "slug": "database-unavailable-after-shutting-down-a-foundationdb-node",
  "category_id": 7,
  "word_count": 2858,
  "deleted_at": null,
  "user_id": 714,
  "featured_link": null,
  "pinned_globally": false,
  "pinned_at": null,
  "pinned_until": null,
  "image_url": null,
  "slow_mode_seconds": 0,
  "draft": null,
  "draft_key": "topic_2113",
  "draft_sequence": null,
  "unpinned": null,
  "pinned": false,
  "current_post_number": 1,
  "highest_post_number": 18,
  "deleted_by": null,
  "actions_summary": [
    {
      "id": 4,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 8,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 10,
      "count": 0,
      "hidden": false,
      "can_act": false
    },
    {
      "id": 7,
      "count": 0,
      "hidden": false,
      "can_act": false
    }
  ],
  "chunk_size": 20,
  "bookmarked": false,
  "topic_timer": null,
  "message_bus_last_id": 0,
  "participant_count": 4,
  "show_read_indicator": false,
  "thumbnails": null,
  "slow_mode_enabled_until": null,
  "tags_disable_ads": false,
  "related_topics": [
    {
      "fancy_title": "Fdb cluster is unavailable after delete a disk",
      "id": 2232,
      "title": "Fdb cluster is unavailable after delete a disk",
      "slug": "fdb-cluster-is-unavailable-after-delete-a-disk",
      "posts_count": 4,
      "reply_count": 1,
      "highest_post_number": 4,
      "image_url": null,
      "created_at": "2020-07-07T09:35:29.720Z",
      "last_posted_at": "2020-07-09T08:38:11.028Z",
      "bumped": true,
      "bumped_at": "2020-07-09T09:28:06.173Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 1154,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 585,
            "username": "ssb",
            "name": "Shunbo Shi",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ssb/{size}/656_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 166,
            "username": "gaurav",
            "name": "gaurav",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/g/b487fb/{size}.png",
            "trust_level": 3
          }
        }
      ]
    },
    {
      "fancy_title": "Segmentation fault error and broken cluster",
      "id": 483,
      "title": "Segmentation fault error and broken cluster",
      "slug": "segmentation-fault-error-and-broken-cluster",
      "posts_count": 17,
      "reply_count": 12,
      "highest_post_number": 17,
      "image_url": null,
      "created_at": "2018-05-31T15:34:28.123Z",
      "last_posted_at": "2018-06-11T17:31:13.656Z",
      "bumped": true,
      "bumped_at": "2018-06-11T17:31:13.656Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 2,
      "views": 4331,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 211,
            "username": "brk0v",
            "name": "Viacheslav Biriukov",
            "avatar_template": "/user_avatar/forums.foundationdb.org/brk0v/{size}/173_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 12,
            "username": "ajbeamon",
            "name": "A.J. Beamon",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
            "admin": true,
            "trust_level": 4
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 156,
            "username": "spullara",
            "name": "Sam Pullara",
            "avatar_template": "/user_avatar/forums.foundationdb.org/spullara/{size}/125_2.png",
            "trust_level": 2
          }
        }
      ]
    },
    {
      "fancy_title": "Foundationdb seems keep reinitialising itself after client hang",
      "id": 1437,
      "title": "Foundationdb seems keep reinitialising itself after client hang",
      "slug": "foundationdb-seems-keep-reinitialising-itself-after-client-hang",
      "posts_count": 6,
      "reply_count": 2,
      "highest_post_number": 6,
      "image_url": null,
      "created_at": "2019-06-10T10:10:13.209Z",
      "last_posted_at": "2019-06-26T18:08:03.629Z",
      "bumped": true,
      "bumped_at": "2019-06-26T18:08:03.629Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 1,
      "views": 1222,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": null,
          "description": "Original Poster",
          "user": {
            "id": 602,
            "username": "ppggff",
            "name": "ppggff",
            "avatar_template": "/user_avatar/forums.foundationdb.org/ppggff/{size}/855_2.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 166,
            "username": "gaurav",
            "name": "gaurav",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/g/b487fb/{size}.png",
            "trust_level": 3
          }
        },
        {
          "extras": "latest",
          "description": "Most Recent Poster",
          "user": {
            "id": 13,
            "username": "alexmiller",
            "name": "Alex Miller",
            "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
            "trust_level": 4
          }
        }
      ]
    },
    {
      "fancy_title": "Locking coordination state. Verify that a majority of coordinattion server process are active. Single machine",
      "id": 2560,
      "title": "Locking coordination state. Verify that a majority of coordinattion server process are active. Single machine",
      "slug": "locking-coordination-state-verify-that-a-majority-of-coordinattion-server-process-are-active-single-machine",
      "posts_count": 5,
      "reply_count": 2,
      "highest_post_number": 5,
      "image_url": null,
      "created_at": "2021-02-16T23:20:12.154Z",
      "last_posted_at": "2021-03-08T20:52:08.046Z",
      "bumped": true,
      "bumped_at": "2021-03-08T20:52:08.046Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 0,
      "views": 1182,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 885,
            "username": "jds",
            "name": "JD S",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/j/b19c9b/{size}.png",
            "trust_level": 1
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 448,
            "username": "dongxinEric",
            "name": "Xin Dong",
            "avatar_template": "/user_avatar/forums.foundationdb.org/dongxineric/{size}/434_2.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 14,
            "username": "andrew.noyes",
            "name": "",
            "avatar_template": "/user_avatar/forums.foundationdb.org/andrew.noyes/{size}/443_2.png",
            "trust_level": 2
          }
        }
      ]
    },
    {
      "fancy_title": "Fdbserver error in a cluster with double redundancy",
      "id": 2348,
      "title": "Fdbserver error in a cluster with double redundancy",
      "slug": "fdbserver-error-in-a-cluster-with-double-redundancy",
      "posts_count": 3,
      "reply_count": 1,
      "highest_post_number": 3,
      "image_url": null,
      "created_at": "2020-09-20T18:50:42.932Z",
      "last_posted_at": "2020-09-22T07:33:44.911Z",
      "bumped": true,
      "bumped_at": "2020-09-22T11:25:55.307Z",
      "archetype": "regular",
      "unseen": false,
      "pinned": false,
      "unpinned": null,
      "visible": true,
      "closed": false,
      "archived": false,
      "bookmarked": null,
      "liked": null,
      "tags": [],
      "tags_descriptions": {},
      "like_count": 3,
      "views": 859,
      "category_id": 7,
      "featured_link": null,
      "has_accepted_answer": false,
      "posters": [
        {
          "extras": "latest",
          "description": "Original Poster, Most Recent Poster",
          "user": {
            "id": 714,
            "username": "tuk",
            "name": "",
            "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png",
            "trust_level": 2
          }
        },
        {
          "extras": null,
          "description": "Frequent Poster",
          "user": {
            "id": 14,
            "username": "andrew.noyes",
            "name": "",
            "avatar_template": "/user_avatar/forums.foundationdb.org/andrew.noyes/{size}/443_2.png",
            "trust_level": 2
          }
        }
      ]
    }
  ],
  "summarizable": false,
  "can_vote": false,
  "vote_count": 0,
  "user_voted": false,
  "discourse_zendesk_plugin_zendesk_id": null,
  "discourse_zendesk_plugin_zendesk_url": "https://your-url.zendesk.com/agent/tickets/",
  "details": {
    "can_edit": false,
    "notification_level": 1,
    "participants": [
      {
        "id": 714,
        "username": "tuk",
        "name": "",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png",
        "post_count": 9,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 2
      },
      {
        "id": 12,
        "username": "ajbeamon",
        "name": "A.J. Beamon",
        "avatar_template": "/user_avatar/forums.foundationdb.org/ajbeamon/{size}/13_2.png",
        "post_count": 6,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "admin": true,
        "trust_level": 4
      },
      {
        "id": 810,
        "username": "amanda",
        "name": "Amanda",
        "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/a/67e7ee/{size}.png",
        "post_count": 2,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 2
      },
      {
        "id": 13,
        "username": "alexmiller",
        "name": "Alex Miller",
        "avatar_template": "/user_avatar/forums.foundationdb.org/alexmiller/{size}/326_2.png",
        "post_count": 1,
        "primary_group_name": null,
        "flair_name": null,
        "flair_url": null,
        "flair_color": null,
        "flair_bg_color": null,
        "flair_group_id": null,
        "trust_level": 4
      }
    ],
    "created_by": {
      "id": 714,
      "username": "tuk",
      "name": "",
      "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/t/b5ac83/{size}.png"
    },
    "last_poster": {
      "id": 810,
      "username": "amanda",
      "name": "Amanda",
      "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/a/67e7ee/{size}.png"
    },
    "links": [
      {
        "url": "https://github.com/apple/foundationdb/issues/2480",
        "title": "Provide tooling to recover from a corrupted (non-recoverable) fdb cluster \u00b7 Issue #2480 \u00b7 apple/foundationdb \u00b7 GitHub",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 21,
        "user_id": 12,
        "domain": "github.com",
        "root_domain": "github.com"
      },
      {
        "url": "https://forums.foundationdb.org/t/can-i-remove-a-process/1428/7",
        "title": "Can I remove a process?",
        "internal": true,
        "attachment": false,
        "reflection": false,
        "clicks": 13,
        "user_id": 714,
        "domain": "forums.foundationdb.org",
        "root_domain": "foundationdb.org"
      },
      {
        "url": "https://drive.google.com/uc?id=1tT0GcnO9J-632rsqNb3I4odAyXeBW1cF&export=download",
        "title": null,
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 5,
        "user_id": 714,
        "domain": "drive.google.com",
        "root_domain": "google.com"
      },
      {
        "url": "https://drive.google.com/drive/folders/1bqElC70rm3Fxuihoou37ULJUZIdz62Fy?usp=sharing",
        "title": "fdb_corrupt - Google Drive",
        "internal": false,
        "attachment": false,
        "reflection": false,
        "clicks": 4,
        "user_id": 714,
        "domain": "drive.google.com",
        "root_domain": "google.com"
      }
    ]
  },
  "bookmarks": []
}